### ISSUE TITLE
Sweet Sixteen digital outputs nonfunctional

### ISSUE THREAD

**Issue by ghost** [M4ngu/Sweet-Sixteen#2]
While running the 16n 2.1 firmware, Crow sees SS via i2c and can poll its faders, but their value is always 0.0.
The web editor can see SS, but the value are all 0 as well. I can configure the CC indexes and other global settings but the faders don't seem to be read digitally at all.

I've tried all the other firmwares I can find. While running Sweet_mkii, the web editor says "It looks like a 16n is trying to connect, but may have a corrupt memory." 

All analog inputs and outputs work as they're supposed to.

Any thoughts? THanks!

**Comment by M4ngu** [comment]
Sweet mkII is for the GESS expander and does not support the web app, I recommend the 2.0.1 version from my github,
https://github.com/M4ngu/Sweet-Sixteen/tree/master/firmware
