### ISSUE TITLE
Sweet_3 firmware compatibility?

### ISSUE THREAD

**Issue by chuchana** [M4ngu/Sweet-Sixteen#3]
Hi! Since there is no mention that it isn't, I assume the Sweet_3 firmware is compatible with the original Sweet Sixteen. Is that correct?

**Comment by M4ngu** [comment]
if you mean the first version, yes it it, the GESS part of the code isn't necessary (it could be compiled commenting the line with '#define gess...' but it won't do any bad indeed

**Comment by chuchana** [comment]
great, thanks!
