### ISSUE TITLE
MIDI to CV

### ISSUE THREAD

**Issue by Bubobubobubobubo** [M4ngu/Sweet-Sixteen#6]
Hi, 

Is it possible to reprogram the Sweet Sixteen to act as a MIDI to CV converter? I would like to use the same CC values but in the other direction :) Meaning, a CC from 0 to 127 converted into a 0-8V on the corresponding output. If so, could you provide some guidance on the process to rewrite the code to do so? 

Thanks a lot, nice module!

**Comment by M4ngu** [comment]
The digital part of this module controls only the MIDI and the i2C data. The faders, CV in & out circuit is fully analog, so modifications like changing the output voltage range can’t be done via firmware. 
This module can do CV to midi (among many other functions) NOT midi to CV.

**Comment by Bubobubobubobubo** [comment]
OK! Thanks!
